/**
  I Ching Hexagram Dictionary
**/
var iching = {
  hex01:{
    hexCode:"&#19904;",
    hexName:"1. Ch'ien / The Creative",
    allLines:["yang","yang","yang","yang","yang","yang"],
    judgment:"The Creative works sublime success.  Furthering through perseverance.",
    image:"The movement of heaven is full of power.  Thus the superior individual makes oneself strong and untiring",
    line5:"Nine at the top means:  Arrogant dragon will have cause to repent.",
    line4:"Nine in the fifth place means:  Flying dragons in the heavens.  It furthers you to see the great one.",
    line3:"Nine in the fourth place means:  Wavering flight over the depths.  No blame.",
    line2:"Nine in the third place means:  All day long the superior one is creatively active.  At nightfall the superior one's mind is beset with cares.  Danger.  No blame.",
    line1:"Nine in the second place means:  Dragon appearing in the field.  It furthers you to see the great one.",
    line0:"Nine at the beginning means:  Hidden dragon.  Do not act.",
    special:"All lines are nine:  There appears a flight of dragons without heads.  Good fortune."
  },
  hex02:{
    hexCode:"&#19905;",
    hexName:"2. K'un / The Receptive",
    allLines:["yin","yin","yin","yin","yin","yin"],
	judgment:"The Receptive brings about sublime success,  Furthering through the perseverance of a mare.  If the superior one undertakes something and tries to lead,  The superior one goes astray;  but, if one follows, one finds guidance.  It is favorable to find friends in the east and north.  Quiet perseverance brings good fortune.",
	image:"The earth's condition is receptive devotion.  Thus, the superior one who has breadth of character  Carries the outer world.",
    line5:"Six at the top means:  Dragons fight in the meadow.   Their blood is black and yellow.",
    line4:"Six in the fifth place means:  A yellow lower garment brings supreme good fortune.",
    line3:"Six in the fourth place means:  A tied-up sack.  No blame, no praise.",
    line2:"Six in the third place means:  Hidden lines.  One is able to remain persevering.  If by change you are in the service of a king,  Seek not works, but bring to completion.",
    line1:"Six in the second place means:  Straight, square, great.  Without purpose,  Yet nothing remains unfurthered.",
    line0:"Six at the beginning means:  When there is hoarfrost underfoot,  Solid ice is not far off.",
    special:"All lines are six:  Lasting perseverance furthers."
  },
  hex03:{
    hexCode:"&#19906;",
    hexName:"3. Chun / Difficulty at the Beginning",
    allLines:["yang","yin","yin","yin","yang","yin"],
	judgment:"Difficulty at the Beginning works supreme success,  Furthering through perseverance.  Nothing should be undertaken.  It furthers one to appoint helpers.",
	image:"Clouds and thunder:  The image of Difficulty at the Beginning.  Thus the superior one  Brings order out of confusion.",
    line5:"Six at the top means:  Horse and wagon part.  Bloody tears flow.",
    line4:"Nine in the fifth place means:  Difficulties in blessing.  A little perseverance brings good fortune.  Great perseverance brings misfortune.",
    line3:"Six in the fourth place means:  Horse and wagon part.  Strive for union.  To go brings good fortune.  Everything acts to further.",
    line2:"Six in the third place means:  Whoever hunts deer without the forester  Only loses their way in the forest.  The superior one understands the signs of the time  And prefers to desist.  To go on brings humiliation.",
    line1:"Six in the second place means:  Difficulties pile up.  Horse and wagon part.  He is not a robber;  He wants to woo when the time comes.  The maiden is chaste,  She does not pledge herself.  Ten years -- then she pledges herself.",
    line0:"Nine at the beginning means:  Hesitation and hindrance.  It furthers one to remain persevering.  It furthers one to appoint helpers."
  },
  hex04:{
    hexCode:"&#19907;",
    hexName:"4. Méng / Youthful Folly",
    allLines:["yin","yang","yin","yin","yin","yang"],
	judgment:"Youthful Folly has success.  It is not I who seek the young fool;  The young fool seeks me.  At the first oracle I inform.  If asked two or three times, it is importunity.  If one importunes, I give no information.  Perseverance furthers.",
	image:"A spring wells up at the foot of the mountain:  The image of Youth.  Thus the superior one fosters their character  By thoroughness in everything that they do.",
    line5:"Nine at the top means:  In punishing folly  It does not further one  To commit transgressions.  The only thing that furthers  Is to prevent transgressions.",
    line4:"Six in the fifth place means:  Childlike folly brings good fortune.",
    line3:"Six in the fourth place means:  Entangled folly brings humiliation.",
    line2:"Six in the third place means:  Take not a maiden who, when she sees a man of bronze,  Loses possession of herself.  Nothing furthers.",
    line1:"Nine in the second place means:  To bear with fools in kindliness brings good fortune.  To know how to take women  Brings good fortune.  The son is capable of taking charge of the household.",
    line0:"Six at the beginning means:  To make a fool develop  It furthers one to apply discipline.  The fetters should be removed.  To go on in this way brings humiliation."
  },
  hex05:{
    hexCode:"&#19908;",
    hexName:"5. Hsü / Waiting (Nourishment)",
    allLines:["yang","yang","yang","yin","yang","yin"],
	judgment:"Waiting.  If you are sincere,  You have light and success.  Perseverance brings good fortune.  It furthers one to cross the great water.",
	image:"Clouds rise up to heaven:  The image of Waiting.  Thus the superior one eats and drinks,  Is joyous and of good cheer.",
    line5:"Six at the top means:  One falls into the pit.  Three uninvited guests arrive.  Honor them, and in the end there will be good fortune.",
    line4:"Nine in the fifth place means:  Waiting at meat and drink.  Perseverance brings good fortune.",
    line3:"Six in the fourth place means:  Waiting in blood.  Get out of the pit.",
    line2:"Nine in the third place means:  Waiting in the mud  Brings about the arrival of the enemy.",
    line1:"Nine in the second place means:  Waiting on the sand.  There is some gossip.  The end brings good fortune.",
    line0:"Nine at the beginning means:  Waiting in the meadow.  It furthers one to abide in what endures.  No blame."
  },
  hex06:{
    hexCode:"&#19909;",
    hexName:"6. Sung / Conflict",
    allLines:["yin","yang","yin","yang","yang","yang"],
	judgment:"Conflict.  You are sincere  And are being obstructed.  A cautious halt halfway brings good fortune.  Going through to the end brings misfortune.  It furthers to see the great one.  It does not further one to cross the great water.",
	image:"Heaven and water go their opposite ways:  The image of Conflict.  Thus in all transactions the superior one  Carefully considers the beginning.",
    line5:"Nine at the top means:  Even if by change a leather belt is bestowed on one,  By the end of a morning  It will have been snatched away three times.",
    line4:"Nine in the fifth place means:  To contend before him  Brings supreme good fortune.",
    line3:"Nine in the fourth place means:  One cannot engage in conflict.  One turns back and submits to fate,  Changes one's attitude,  And finds peace in perseverance.  Good fortune.",
    line2:"Six in the third place means:  To nourish oneself on ancient virtue induces perseverance.  Danger.  In the end, good fortune comes.  If by chance you are in the service of a king,  Seek not works.",
    line1:"Nine in the second place means:  One cannot engage in conflict;  One returns home, gives way.  The people of the town,  Three hundred households,  Remain free of guilt.",
    line0:"Six at the beginning means:  If one does not perpetuate the affair,  There is a little gossip.  In the end, good fortune comes."
  },
  hex07:{
    hexCode:"&#19910;",
    hexName:"7. Shih / The Army",
    allLines:["yin","yang","yin","yin","yin","yin"],
	judgment:"The Army.  The army needs perseverance  And a strong man.  Good fortune without blame.",
	image:"In the middle of the earth is water:  The image of The Army.  Thus the superior one increases their masses  By generosity toward the people.",
    line5:"Six at the top means:  The great prince issues commands,  Founds states, vests families with fiefs.  Inferior people should not be employed.",
    line4:"Six in the fifth place means:  There is game in the field.  It furthers one to catch it.  Without blame.  Let the eldest lead the army.  The younger transports corpses;  Then perseverance brings misfortune.",
    line3:"Six in the fourth place means:  The army retreats.  No blame.",
    line2:"Six in the third place means:  Perchance the army carries corpses in the wagon.  Misfortune.",
    line1:"Nine in the second place means:  In the midst of the army.  Good fortune.  No blame.  The kind bestows a triple decoration.",
    line0:"Six at the beginning means:  An army must set forth in proper order.  If the order is not good, misfortune threatens."
  },
  hex08:{
    hexCode:"&#19911;",
    hexName:"8. Pi / Holding Together [Union]",
    allLines:["yin","yin","yin","yin","yang","yin"],
	judgment:"Holding Together brings good fortune.  Inquire of the oracle once again  Whether you possess sublimity, constancy, and perseverance;  Then there is no blame.  Those who are uncertain gradually join.  Whoever comes too late  Meets with misfortune.",
	image:"On the earth is water;  The image of Holding Together.  Thus the kings of antiquity  Bestowed the different states as fiefs  And cultivated friendly relations  With the feudal lords.",
    line5:"Six at the top means:  He finds no head for holding together.  Misfortune.",
    line4:"Nine in the fifth place means:  Manifestation of holding together.  In the hunt the king uses beaters on three sides only  And foregoes game that runs off in front.  The citizens need no warning.  Good fortune.",
    line3:"Six in the fourth place means:  Hold to him outwardly also.  Perseverance brings good fortune.",
    line2:"Six in the third place means:  You hold together with the wrong people.",
    line1:"Six in the second place means:  Hold to him inwardly.  Perseverance brings good fortune.",
    line0:"Six at the beginning means:  Hold to him in truth and loyalty;  This is without blame.  Truth, like a full earthen bowl:  Thus in the end  Good fortune comes from without."
  },
  hex09:{
    hexCode:"&#19912;",
    hexName:"9. Hsiao Ch'u / The Taming Power of the Small",
    allLines:["yang","yang","yang","yin","yang","yang"],
	judgment:"The Taming Power of the Small  Has success.  Dense clouds, no rain from our western region.",
	image:"The wind drives across heaven:  The image of The Taming Power of the Small.  Thus the superior man  Refines the outward aspect of his nature.",
    line5:"Nine at the top means:  The rain comes, there is rest.  This is due to the lasting effect of character.  Perseverance brings the woman into danger.  The moon is nearly full.  If the superior one persists,  Misfortune comes.",
    line4:"Nine in the fifth place means:  If you are sincere and loyally attached,  You are rich in your neighbor.",
    line3:"Six in the fourth place means:  If you are sincere, blood vanishes and fear gives way.  No blame.",
    line2:"Nine in the third place means:  The spokes burst out of the wagon wheels.  Man and wife roll their eyes.",
    line1:"Nine in the second place means:  He allows himself to be drawn into returning.  Good fortune.",
    line0:"Nine at the beginning means:  Return to the way.  How could there be blame in this?  Good fortune."
  },
  hex10:{
    hexCode:"&#19913;",
    hexName:"10. Lü / Treading [Conduct]",
    allLines:["yang","yang","yin","yang","yang","yang"],
	judgment:"Treading.  Treading upon the tail of the tiger.  It does not bite the person.  Success.",
	image:"Heaven above, the lake below:  The image of Treading.  Thus the superior one discriminates between high and low,  And thereby fortifies the thinking of the people.",
    line5:"Nine at the top means:  Look to your conduct and weigh the favorable signs.  When everything is fulfilled, supreme good fortune comes.",
    line4:"Nine in the fifth place means:  Resolute conduct.  Perseverance with awareness of danger.",
    line3:"Nine in the fourth place means:  He treads on the tail of the tiger.  Caution and circumspection  Lead ultimately to good fortune.",
    line2:"Six in the third place means:  A one-eyed man is able to see,  A lame man is able to tread.  He treads on the tail of the tiger.  The tiger bites the man.  Misfortune.  Thus does a warrior act on behalf of his great prince.",
    line1:"Nine in the second place means:  Treading a smooth, level course.  The perseverance of a dark man  Brings good fortune.",
    line0:"Nine at the beginning means:  Simple conduct.  Progress without blame."
  },
  hex11:{
    hexCode:"&#19914;",
    hexName:"11. T'ai / Peace",
    allLines:["yang","yang","yang","yin","yin","yin"],
	judgment:"Peace.  The small departs,  The great approaches.  Good fortune. Success.",
	image:"Heaven and earth unite:  the image of Peace.  Thus the ruler  Divides and completes the course of heaven and earth;  He furthers and regulates the gifts of heaven and earth,  And so aids the people.",
    line5:"Six at the top means:  The wall falls back into the moat.  Use no army now.  Make your commands known within your own town.  Perseverance brings humiliation.",
    line4:"Six in the fifth place means:  The sovereign I  Gives his daughter in marriage.  This brings blessing  And supreme good fortune.",
    line3:"Six in the fourth place means:  He flutters down, not boasting of his wealth,  Together with his neighbor,  Guileless and sincere.",
    line2:"Nine in the third place means:  No plain not followed by a slope,  No going not followed by a return.  He who remains persevering in danger  Is without blame.  Do not complain about this truth;  Enjoy the good fortune you still possess.",
    line1:"Nine in the second place means:  Bearing with the uncultured in gentleness,  Fording the river with resolution,  Not neglecting what is distant,  Not regarding one's companions:  Thus one may manage to walk in the middle.",
    line0:"Nine at the beginning means:  When ribbon grass is pulled up, the sod comes with it.  Each according to their kind.  Undertakings bring good fortune."
  },
  hex12:{
    hexCode:"&#19915;",
    hexName:"12. P'i / Standstill [Stagnation]",
    allLines:["yin","yin","yin","yang","yang","yang"],
	judgment:"Standstill.  Evil people do not further  The perseverance of the superior one.  The great departs; the small approaches.",
	image:"Heaven and earth do not unite:  The image of Standstill.  Thus the superior one falls back upon inner worth  In order to escape the difficulties.  One does not permit oneself to be honored with revenue.",
    line5:"Nine at the top means:  The standstill comes to an end.  First standstill, then good fortune.",
    line4:"Nine in the fifth place means:  Standstill is giving way.  Good fortune for the great one.  'What if it should fail, what if it should fail?'  In this way one ties it to a cluster of mulberry shoots.",
    line3:"Nine in the fourth place means:  One who acts at the command of the highest  Remains without blame.  Those of like mind partake of the blessing.",
    line2:"Six in the third place means:  They bear shame.",
    line1:"Six in the second place means:  They bear and endure;  This means good fortune for inferior people.  The standstill serves to help the great one to attain success.",
    line0:"Six at the beginning means:  When ribbon grass is pulled up, the sod comes with it.  Each according to their kind.  Perseverance brings good fortune and success."
  },
  hex13:{
    hexCode:"&#19916;",
    hexName:"13. T'ung Jên / Fellowship with Others",
    allLines:["yang","yin","yang","yang","yang","yang"],
	judgment:"Fellowship with others in the open.  Success.  It furthers one to cross the great water.  The perseverance of the superior one furthers.",
	image:"Heaven together with fire:  The image of Fellowship with Others.  Thus the superior one organizes the clans  And makes distinctions between things.",
    line5:"Nine at the top means:  Fellowship with others in the meadow.  No remorse.",
    line4:"Nine in the fifth place means:  People bound in fellowship first weep and lament,  But afterward they laugh.  After great struggles they succeed in meeting.",
    line3:"Nine in the fourth place means:  He climbs up on his wall;  he cannot attack.  Good fortune.",
    line2:"Nine in the third place means:  One hides weapons in the thicket;  One climbs the high hill in front of it.  For three years one does not rise up.",
    line1:"Six in the second place means:  Fellowship with others in the clan.  Humiliation.",
    line0:"Nine at the beginning means:  Fellowship with others at the gate.  No blame."
  },
  hex14:{
    hexCode:"&#19917;",
    hexName:"14. Ta Yu / Possession in Great Measure",
    allLines:["yang","yang","yang","yang","yin","yang"],
	judgment:"Possession in Great Measure.  Supreme success",
	image:"Fire in heaven above:  The image of Possession in Great Measure.  Thus the superior one curbs evil and furthers good,  And thereby obeys the benevolent will of heaven.",
    line5:"Nine at the top means:  One is blessed by heaven.  Good fortune.  Nothing that does not further.",
    line4:"Six in the fifth place means:  One whose truth is accessible, yet dignified,  Has good fortune.",
    line3:"Nine in the fourth place means:  One makes a difference  Between oneself and one's neighbor.  No blame.",
    line2:"Nine in the third place means:  A prince offers it to the Son of Heaven.  A petty person cannot do this.",
    line1:"Nine in the second place means:  A big wagon for loading.  One may undertake something.  No blame.",
    line0:"Nine at the beginning means:  No relationship with what is harmful;  There is no blame in this.  If one remains conscious of difficulty,  One remains without blame."
  },
  hex15:{
    hexCode:"&#19918;",
    hexName:"15. Ch'ien / Modesty",
    allLines:["yin","yin","yang","yin","yin","yin"],
	judgment:"Modesty creates success.  The superior one carries things through.",
	image:"Within the earth, a mountain:  The image of Modesty.  Thus the superior one reduces that which is too much,  And augments that which is too little.  The superior one weighs things and makes them equal.",
    line5:"Six at the top means:  Modesty that comes to expression.  It is favorable to set armies marching  To chastise one's own city and one's country.",
    line4:"Six in the fifth place means:  No boasting of wealth before one's neighbor.  It is favorable to attack with force.  Nothing that would not further.",
    line3:"Six in the fourth place means:  Nothing that would not further modesty  In movement.",
    line2:"Nine in the third place means:  A superior person of modesty and merit  Carries things to conclusion.  Good fortune.",
    line1:"Six in the second place means:  Modesty that comes to expression.  Perseverance brings good fortune.",
    line0:"Six at the beginning means:  A superior person modest about their modesty  May cross the great water.  Good fortune."
  },
  hex16:{
    hexCode:"&#19919;",
    hexName:"16. Yü / Enthusiasm",
    allLines:["yin","yin","yin","yang","yin","yin"],
	judgment:"Enthusiasm.  It furthers one to install helpers  And to set armies marching.",
	image:"Thunder comes resounding out of the earth:  The image of Enthusiasm.  Thus the ancient kings made music  In order to honor merit,  And offered it with splendor  To the Supreme Deity,  Inviting their ancestors to be present.",
    line5:"Six at the top means:  Deluded enthusiasm.  But if after completion one changes,  There is no blame.",
    line4:"Six in the fifth place means:  Persistently ill, and still does not die.",
    line3:"Nine in the fourth place means:  The source of enthusiasm.  One achieves great things.  Doubt not.  You gather friends around you  As a hair clasp gathers the hair.",
    line2:"Six in the third place means:  Enthusiasm that looks upward creates remorse.  Hesitation brings remorse.",
    line1:"Six in the second place means:  Firm as a rock.  Not a whole day.  Perseverance brings good fortune.",
    line0:"Six at the beginning means:  Enthusiasm that expresses itself  Brings misfortune."
  },
  hex17:{
    hexCode:"&#19920;",
    hexName:"17. Sui / Following",
    allLines:["yang","yin","yin","yang","yang","yin"],
	judgment:"Following has supreme success.  Perseverance furthers.  No blame.",
	image:"Thunder in the middle of the lake:  The image of Following.  Thus the superior one at nightfall  Goes indoors for rest and recuperation.",
    line5:"Six at the top means:  One meets with firm allegiance  And is still further bound.  The king introduces one  To the Western Mountain.",
    line4:"Nine in the fifth place means:  Sincere in the good.  Good fortune.",
    line3:"Nine in the fourth place means:  Following creates success.  Perseverance brings misfortune.  To go one's way with sincerity brings clarity.  How could there be blame in this?",
    line2:"Six in the third place means:  If one clings to the strong man,  One loses the little boy.  Through following one finds what one seeks.  It furthers one to remain persevering.",
    line1:"Six in the second place means:  If one clings to the little boy,  One loses the strong man.",
    line0:"Nine at the beginning means:  The standard is changing.  Perseverance brings good fortune.  To go out of the door in company  Produces deeds."
  },
  hex18:{
    hexCode:"&#19921;",
    hexName:"18. Ku / Work on What Has Been Spoiled [Decay]",
    allLines:["yin","yang","yang","yin","yin","yang"],
	judgment:"Work on What Has Been Spoiled  Has supreme success.  It furthers one to cross the great water.  Before the starting point, three days.  After the starting point, three days.",
	image:"The wind blows low on the mountain:  The image of Decay.  Thus the superior one stirs up the people  And strengthens their spirit.",
    line5:"One does not serve kings and princes,  Sets oneself higher goals.",
    line4:"Six in the fifth place means:  Setting right what has been spoiled by the father.  One meets with praise.",
    line3:"Six in the fourth place means:  Tolerating what has been spoiled by the father.  In continuing one sees humiliation.",
    line2:"Nine in the third place means:  Setting right what has been spoiled by the father.  There will be little remorse.  No great blame.",
    line1:"Nine in the second place means:  Setting right what has been spoiled by the mother.  One must not be too persevering.",
    line0:"Six at the beginning means:  Setting right what has been spoiled by the father.  If there is a son,  No blame rests upon the departed father.  Danger.  In the end good fortune."
  },
  hex19:{
    hexCode:"&#19922;",
    hexName:"19. Lin / Approach",
    allLines:["yang","yang","yin","yin","yin","yin"],
	judgment:"Approach has supreme success.  Perseverance furthers.  When the eighth month comes,  There will be misfortune.",
	image:"The earth above the lake:  The image of Approach.  Thus the superior one is inexhaustible  In the will to teach,  And without limits  In the tolerance and protection of the people.",
    line5:"Six at the top means:  Greathearted approach.  Good fortune.  No blame.",
    line4:"Six in the fifth place means:  Wise approach.  This is right for a great prince.  Good fortune.",
    line3:"Six in the fourth place means:  Complete approach.  No blame.",
    line2:"Six in the third place means:  Comfortable approach.  Nothing that would further.  If one is induced to grieve over it,  One becomes free of blame.",
    line1:"Nine in the second place means:  Joint approach.  Good fortune.  Everything furthers.",
    line0:"Nine at the beginning means:  Joint approach.  Perseverance brings good fortune."
  },
  hex20:{
    hexCode:"&#19923;",
    hexName:"20. Kuan / Contemplation (View)",
    allLines:["yin","yin","yin","yin","yang","yang"],
	judgment:"Contemplation.  The ablution has been made,  But not yet the offering.  Full of trust they look up to one.",
	image:"The wind blows over the earth:  The image of Contemplation.  Thus the kings of old visited the regions of the world,  Contemplated the people,  And gave them instruction.",
    line5:"Nine at the top means:  Contemplation of one's life.  The superior one is without blame.",
    line4:"Nine in the fifth place means:  Contemplation of my life.  The superior one is without blame.",
    line3:"Six in the fourth place means:  Contemplation of the light of the kingdom.  It furthers one to exert influence as the guest of a king.",
    line2:"Six in the third place means:  Contemplation of my life  Decides the choice  Between advance and retreat.",
    line1:"Six in the second place means:  Contemplation through the crack of the door.  Furthering for the perseverance of a woman.",
    line0:"Six at the beginning means:  Childlike contemplation  For an inferior person, no blame.  For a superior person, humiliation."
  },
  hex21:{
    hexCode:"&#19924;",
    hexName:"21. Shih Ho / Biting Through",
    allLines:["yang","yin","yin","yang","yin","yang"],
	judgment:"Biting Through has success.  It is favorable to let justice be administered.",
	image:"Thunder and lightning:  The image of Biting Through.  Thus the kings of former times made firm the laws  Through clearly defined penalties.",
    line5:"Nine at the top means:  One's neck is fastened in the wooden cangue,  So that one's ears disappear.  Misfortune.",
    line4:"Six in the fifth place means:  Bites on dried lean meat.  Receives yellow gold.  Perseveringly aware of danger.  No blame.",
    line3:"Nine in the fourth place means:  Bites on dried gristly meat.  Receives metal arrows.  It furthers one to be mindful of difficulties  And to be persevering.  Good fortune.",
    line2:"Six in the third place means:  Bites on old dried meat  And strikes on something poisonous.  Slight humiliation.  No blame.",
    line1:"Six in the second place means:  Bites through tender meat,  So that his nose disappears.  No blame.",
    line0:"Nine at the beginning means:  One's feet are fastened in the stocks,  So that one's toes disappear.  No blame."
  },
  hex22:{
    hexCode:"&#19925;",
    hexName:"22. Pi / Grace",
    allLines:["yang","yin","yang","yin","yin","yang"],
	judgment:"Grace has success.  In small matters  It is favorable to undertake something.",
	image:"Fire at the foot of the mountain:  The image of Grace.  Thus does the superior one proceed  When clearing up current affairs.  But he dare not decide controversial issues in this way.",
    line5:"Nine at the top means:  Simple grace.  No blame.",
    line4:"Six in the fifth place means:  Grace in hills and gardens.  The roll of silk is meager and small.  Humiliation, but in the end good fortune.",
    line3:"Six in the fourth place means:  Grace or simplicity?  A white horse comes as if on wings.  He is not a robber,  He will woo at the right time.",
    line2:"Nine in the third place means:  Graceful and moist.  Constant perseverance brings good fortune.",
    line1:"Six in the second place means:  Lends grace to the beard on his chin.",
    line0:"Nine at the beginning means:  He lends grace to his toes, leaves the carriage,  And walks."
  },
  hex23:{
    hexCode:"&#19926;",
    hexName:"23. Po / Splitting Apart",
    allLines:["yin","yin","yin","yin","yin","yang"],
	judgment:"Splitting Apart.  It does not further one  To go anywhere.",
	image:"The mountain rests on the earth:  The image of Splitting Apart.  Thus those above can ensure their position  Only by giving generously to those below.",
    line5:"Nine at the top means:  There is a large fruit still uneaten.  The superior one receives a carriage.  The house of the inferior one is split apart.",
    line4:"Six in the fifth place means:  A shoal of fishes.  Favor comes through the court ladies.  Everything acts to further.",
    line3:"Six in the fourth place means:  The bed is split up to the skin.  Misfortune.",
    line2:"Six in the third place means:  He splits with them.  No blame.",
    line1:"Six in the second place means:  The bed is split at the edge.  Those who persevere are destroyed.  Misfortune.",
    line0:"Six at the beginning means:  The leg of the bed is split.  Those who persevere are destroyed.  Misfortune."
  },
  hex24:{
    hexCode:"&#19927;",
    hexName:"24. Fu / Return (The Turning Point)",
    allLines:["yang","yin","yin","yin","yin","yin"],
	judgment:"Return.  Success.  Going out and coming in without error.  Friends come without blame.  To and fro goes the way.  On the seventh day comes return.  It furthers one to have somewhere to go.",
	image:"Thunder within the earth:  The image of The Turning Point.  Thus the kings of antiquity closed the passes  At the time of solstice.  Merchants and strangers did not go about,  And the ruler  Did not travel through the provinces.",
    line5:"Six at the top means:  Missing the return.  Misfortune.  Misfortune from within and without.  If armies are set marching in this way,  One will in the end suffer a great defeat,  Disastrous for the ruler of the country.  For ten years  It will not be possible to attack again.",
    line4:"Six in the fifth place means:  Noblehearted return.  No remorse.",
    line3:"Six in the fourth place means:  Walking in the midst of others,  One returns alone.",
    line2:"Six in the third place means:  Repeated return.  Danger.  No blame.",
    line1:"Six in the second place means:  Quiet return.  Good fortune.",
    line0:"Nine at the beginning means:  Return from a short distance.  No need for remorse.  Great good fortune."
  },
  hex25:{
    hexCode:"&#19928;",
    hexName:"25. Wu Wang / Innocence (The Unexpected)",
    allLines:["yang","yin","yin","yang","yang","yang"],
	judgment:"Innocence.  Supreme success.  Perseverance furthers.  If someone is not as he should be,  He has misfortune,  And it does not further him  To undertake anything.",
	image:"Under heaven thunder rolls:  All things attain the natural state of innocence.  Thus the kings of old,  Rich in virtue, and in harmony with the time,  Fostered and nourished all beings.",
    line5:"Nine at the top means:  Innocent action brings misfortune.  Nothing furthers.",
    line4:"Nine in the fifth place means:  Use no medicine in an illness  Incurred through no fault of your own.  It will pass of itself.",
    line3:"Nine in the fourth place means:  He who can be persevering  Remains without blame.",
    line2:"Six in the third place means:  Undeserved misfortune.  The cow that was tethered by someone  Is the wanderer's gain, the citizen's loss.",
    line1:"Six in the second place means:  If one does not count on the harvest while plowing,  Nor on the use of the ground while clearing it,  It furthers one to undertake something.",
    line0:"Nine at the beginning means:  Innocent behavior brings good fortune."
  },
  hex26:{
    hexCode:"&#19929;",
    hexName:"26. Ta Ch'u / The Taming Power of the Great",
    allLines:["yang","yang","yang","yin","yin","yang"],
	judgment:"The Taming Power of the Great.  Perseverance furthers.  Not eating at home brings good fortune.  It furthers one to cross the great water.",
	image:"Heaven within the mountain:  The image of The Taming Power of the Great.  Thus the superior one acquaints oneself with many sayings of antiquity  And many deeds of the past,  In order to strengthen one's character thereby",
    line5:"Nine at the top means:  One attains the way of heaven.  Success.",
    line4:"Six in the fifth place means:  The tusk of a gelded boar.  Good fortune.",
    line3:"Six in the fourth place means:  The headboard of a young bull.  Great good fortune.",
    line2:"Nine in the third place means:  A good horse that follows others.  Awareness of danger,  With perseverance, furthers.  Practice chariot driving and armed defense daily.  It furthers one to have somewhere to go.",
    line1:"Nine in the second place means:  The axletrees are taken from the wagon.",
    line0:"Nine at the beginning means:  Danger is at hand.  It furthers one to desist."
  },
  hex27:{
    hexCode:"&#19930;",
    hexName:"27. I / The Corners of the Mouth (Providing Nourishment)",
    allLines:["yang","yin","yin","yin","yin","yang"],
	judgment:"The Corners of the Mouth.  Perseverance brings good fortune.  Pay heed to the providing of nourishment  And to what a person seeks  To fill one's own mouth with.",
	image:"At the foot of the mountain, thunder:  The image of Providing Nourishment.  Thus the superior one is careful of one's words  And temperate in eating and drinking.",
    line5:"Nine at the top means:  The source of nourishment.  Awareness of danger brings good fortune.  It furthers one to cross the great water.",
    line4:"Six in the fifth place means:  Turning away from the path.  To remain persevering brings good fortune.  One should not cross the great water.",
    line3:"Six in the fourth place means:  Turning to the summit  For provision of nourishment  Brings good fortune.  Spying about with sharp eyes  Like a tiger with insatiable craving.  No blame.",
    line2:"Six in the third place means:  Turning away from nourishment.  Perseverance brings misfortune.  Do not act thus for ten years.  Nothing serves to further.",
    line1:"Six in the second place means:  Turning to the summit for nourishment,  Deviating from the path  To seek nourishment from the hill.  Continuing to do this brings misfortune.",
    line0:"Nine at the beginning means:  You let your magic tortoise go,  And look at me with the corners of your mouth drooping.  Misfortune."
  },
  hex28:{
    hexCode:"&#19931;",
    hexName:"28. Ta Kuo / Preponderance of the Great",
    allLines:["yin","yang","yang","yang","yang","yin"],
	judgment:"Preponderance of the Great.  The ridgepole sags to the breaking point.  It furthers one to have somewhere to go.  Success.",
	image:"The lake rises above the trees:  The image of Preponderance of the Great.  Thus the superior man, when he stands alone,  Is unconcerned,  And if he has to renounce the world,  He is undaunted.",
    line5:"Six at the top means:  One must go through the water.  It goes over one's head.  Misfortune.  No blame.",
    line4:"Nine in the fifth place means:  A withered poplar puts forth flowers.  An older woman takes a husband.  No blame. No praise.",
    line3:"The ridgepole is braced.  Good fortune.  If there are ulterior motives, it is humiliating.",
    line2:"Nine in the third place means:  The ridgepole sags to the breaking point.  Misfortune.",
    line1:"Nine in the second place means:  A dry poplar sprouts at the root.  An older man takes a young wife.  Everything furthers.",
    line0:"Six at the beginning means:  To spread white rushes underneath.  No blame."
  },
  hex29:{
    hexCode:"&#19932;",
    hexName:"29. K'an / The Abysmal (Water)",
    allLines:["yin","yang","yin","yin","yang","yin"],
	judgment:"The Abysmal repeated.  If you are sincere, you have success in your heart,  And whatever you do succeeds.",
	image:"Water flows uninterruptedly and reaches its goal:  The image of the Abysmal repeated.  Thus the superior one walks in lasting virtue  And carries on the business of teaching.",
    line5:"Six at the top means:  Bound with cords and ropes,  Shut in between thorn-hedged prison walls:  For three years one does not find the way.  Misfortune.",
    line4:"Nine in the fifth place means:  The abyss is not filled to overflowing,  It is filled only to the rim.  No blame.",
    line3:"Six in the fourth place means:  A jug of wine, a bowl of rice with it;  Earthen vessels  Simply handed in through the window.  There is certainly no blame in this.",
    line2:"Six in the third place means:  Forward and backward, abyss on abyss.  In danger like this, pause at first and wait,  Otherwise you will fall into a pit ion the abyss.  Do not act in this way.",
    line1:"Nine in the second place means:  The abyss is dangerous.  One should strive to attain small things only.",
    line0:"Six at the beginning means:  Repetition of the Abysmal.  In the abyss one falls into a pit.  Misfortune."
  },
  hex30:{
    hexCode:"&#19933;",
    hexName:"30. Li / The Clinging, Fire",
    allLines:["yang","yin","yang","yang","yin","yang"],
	judgment:"The Clinging.  Perseverance furthers.  It brings success.  Care of the cow brings good fortune.",
	image:"That which is bright rises twice:  The image of Fire.  Thus the great one, by perpetuating this brightness,  Illumines the four quarters of the world.",
    line5:"Nine at the top means:  The king uses one to march forth and chastise.  Then it is best to kill the leaders  And take captive the followers.  No blame.",
    line4:"Six in the fifth place means:  Tears in floods, sighing and lamenting.  Good fortune.",
    line3:"Nine in the fourth place means:  Its coming is sudden;  It flames up, dies down, is thrown away.",
    line2:"Nine in the third place means:  In the light of the setting sun,  People either beat the pot and sing  Or loudly bewail the approach of old age.  Misfortune.",
    line1:"Six in the second place means:  Yellow light.  Supreme good fortune.",
    line0:"Nine at the beginning means:  The footprints run crisscross.  If one is seriously intent, no blame."
  },
  hex31:{
    hexCode:"&#19934;",
    hexName:"31. Hsien / Influence (Wooing)",
    allLines:["yin","yin","yang","yang","yang","yin"],
	judgment:"Influence.  Success.  Perseverance furthers.  To take a maiden to wife brings good fortune.",
	image:"A lake on the mountain:  The image of influence.  Thus the superior one encourages people to approach  By the superior one's readiness to receive them.",
    line5:"Six at the top means:  The influence shows itself in the jaws, cheeks, and tongue.",
    line4:"Nine in the fifth place means:  The influence shows itself in the back of the neck.  No remorse.",
    line3:"Nine in the fourth place means:  Perseverance brings good fortune.  Remorse disappears.  If one is agitated in mind,  And one's thoughts go hither and thither,  Only those friends  On whom one fixes one's conscious thoughts  Will follow.",
    line2:"Nine in the third place means:  The influence shows itself in the thighs.  Hold to that which follows it.  To continue is humiliating.",
    line1:"Six in the second place means:  The influence shows itself in the calves of the legs.  Misfortune.  Tarrying brings good fortune.",
    line0:"Six at the beginning means:  The influence shows itself in the big toe."
  },
  hex32:{
    hexCode:"&#19935;",
    hexName:"32. Hêng / Duration",
    allLines:["yin","yang","yang","yang","yin","yin"],
	judgment:"Duration.  Success.  No blame.  Perseverance furthers.  It furthers one to have somewhere to go.",
	image:"Thunder and wind:  the image of Duration.  Thus the superior one stands firm  And does not change direction.",
    line5:"Six at the top means:  Restlessness as an enduring condition brings misfortune.",
    line4:"Six in the fifth place means:  Giving duration to one's character through perseverance.  This is good fortune for a woman, misfortune for a man.",
    line3:"Nine in the fourth place means:  No game in the field.",
    line2:"Nine in the third place means:  One who does not give duration to their character  Meets with disgrace.  Persistent humiliation.",
    line1:"Nine in the second place means:  Remorse disappears.",
    line0:"Six at the beginning means:  Seeking duration too hastily brings misfortune persistently.  Nothing that would further."
  },
  hex33:{
    hexCode:"&#19936;",
    hexName:"33. Tun / Retreat",
    allLines:["yin","yin","yang","yang","yang","yang"],
	judgment:"Retreat.  Success.  In what is small, perseverance furthers.  ",
	image:"Mountain under heaven:  the image of Retreat.  Thus the superior one keeps the inferior one at a distance,  Not angrily but with reserve.",
    line5:"Nine at the top means:  Cheerful retreat.  Everything serves to further.",
    line4:"Nine in the fifth place means:  Friendly retreat.  Perseverance brings good fortune.",
    line3:"Nine in the fourth place means:  Voluntary retreat brings good fortune to the superior one.  And downfall to the inferior one.",
    line2:"Nine in the third place means:  A halted retreat  Is nerve-wracking and dangerous.  To retain people as men- and maidservants  Brings good fortune.",
    line1:"Six in the second place means:  He holds him fast with yellow oxhide.  No one can tear him loose.",
    line0:"Six at the beginning means:  At the tail in retreat.  This is dangerous.  One must not wish to undertake anything."
  },
  hex34:{
    hexCode:"&#19937;",
    hexName:"34. Ta Chuang / The Power of the Great",
    allLines:["yang","yang","yang","yang","yin","yin"],
	judgment:"The Power of the Great.  Perseverance furthers.",
	image:"Thunder in heaven above:  The image of The Power of the Great.  Thus the superior one does not tread upon paths  That do not accord with established order.",
    line5:"Six at the top means:  A goat butts against a hedge.  It cannot go backward, it cannot go forward.  Nothing serves to further.  If one notes the difficulty, this brings good fortune.",
    line4:"Six in the fifth place means:  Loses the goat with ease.  No remorse.",
    line3:"Nine in the fourth place means:  Perseverance brings good fortune.  Remorse disappears.  The hedge opens; there is no entanglement.  Power depends upon the axle of a big cart.",
    line2:"Nine in the third place means:  The inferior one works through power.  The superior one does not act thus.  To continue is dangerous.  A goat butts against a hedge  And gets its horns entangled.",
    line1:"Nine in the second place means:  Perseverance brings good fortune.",
    line0:"Nine at the beginning means:  Power in the toes.  Continuing brings misfortune.  This is certainly true."
  },
  hex35:{
    hexCode:"&#19938;",
    hexName:"35. Chin / Progress",
    allLines:["yin","yin","yin","yang","yin","yang"],
	judgment:"Progress.  The powerful prince  Is honored with horses in large numbers.  In a single day he is granted audience three times.",
	image:"The sun rises over the earth:  The image of Progress.  Thus the superior one  brightens their bright virtue.",
    line5:"Nine at the top means:  Making progress with the horns is permissible  Only for the purpose of punishing one's own city.  To be conscious of danger brings good fortune.  No blame.  Perseverance brings humiliation.",
    line4:"Six in the fifth place means:  Remorse disappears.  Take not gain and loss to heart.  Undertakings bring good fortune.  Everything serves to further.",
    line3:"Nine in the fourth place means:  Progress like a hamster.  Perseverance brings danger.",
    line2:"Six in the third place means:  All are in accord.  Remorse disappears.",
    line1:"Six in the second place means:  Progressing, but in sorrow.  Perseverance brings good fortune.  Then one obtains great happiness from one's ancestress.",
    line0:"Six at the beginning means:  Progressing, but turned back.  Perseverance brings good fortune.  If one meets with no confidence, one should remain calm.  No mistake."
  },
  hex36:{
    hexCode:"&#19939;",
    hexName:"36. Ming I / Darkening of the Light",
    allLines:["yang","yin","yang","yin","yin","yin"],
	judgment:"Darkening of the Light.  In adversity  It furthers one to be persevering.",
	image:"The light has sunk into the earth:  The image of Darkening of the Light.  Thus does the superior one live with the great mass:  veiling one's light, yet still shining.",
    line5:"Six at the top means:  Not light but darkness.  First one climbed up to heaven,  Then plunged into the depths of the earth.",
    line4:"Six in the fifth place means:  Darkening of the light as with Prince Chi.  Perseverance furthers.",
    line3:"Six in the fourth place means:  One penetrates the left side of the belly.  One gets at the very heart of the darkening of the light,  And leaves gate and courtyard.",
    line2:"Nine in the third place means:  Darkening of the light during the hunt in the south.  Their great leader is captured.  One must not expect perseverance too soon.",
    line1:"Six in the second place means:  Darkening of the light injures one in the left thigh.  One gives aid with the strength of a horse.  Good fortune.",
    line0:"Nine at the beginning means:  Darkening of the light during flight.  He lowers his wings.  The superior one does not eat for three days  On their wanderings.  But the superior one has somewhere to go.  The host has occasion to gossip about the superior one."
  },
  hex37:{
    hexCode:"&#19940;",
    hexName:"37. Chia Jên / The Family [The Clan]",
    allLines:["yang","yin","yang","yin","yang","yang"],
	judgment:"The Family.  The perseverance of the woman furthers.",
	image:"Wind comes forth from fire:  The image of The Family.  Thus the superior one has substance in their words  And duration in their way of life.",
    line5:"Nine at the top means:  His work commands respect.  In the end good fortune comes.",
    line4:"Nine in the fifth place means:  As a king he approaches his family.  Fear not.  Good fortune.",
    line3:"Six in the fourth place means:  She is the treasure of the house.  Great good fortune.",
    line2:"Nine in the third place means:  When tempers flare up in the family,  Too great severity brings remorse.  Good fortune nonetheless.  When woman and child dally and laugh,  It leads in the end to humiliation.",
    line1:"Six in the second place means:  She should not follow her whims.  She must attend within to the food.  Perseverance brings good fortune.",
    line0:"Nine at the beginning means:  Firm seclusion within the family.  Remorse disappears."
  },
  hex38:{
    hexCode:"&#19941;",
    hexName:"38. K'uei / Opposition",
    allLines:["yang","yang","yin","yang","yin","yang"],
	judgment:"Opposition.  In small matters, good fortune.",
	image:"Above fire; below, the lake:  The image of Opposition.  Thus amid all fellowship  The superior one retains individuality.",
    line5:"Nine at the top means:  Isolated through opposition,  One sees one's companion as a pig covered with dirt,  As a wagon full of devils.  First one draws a bow against the companion.  Then one lays the bow aside.  The person is not a robber and will woo at the right time.  As one goes, rain falls; then good fortune comes.",
    line4:"Six in the fifth place means:  Remorse disappears.  The companion bites their way through the wrappings.  If one goes to them,  How could it be a mistake?",
    line3:"Nine in the fourth place means:  Isolated through opposition,  One meets a like-minded person  With whom one can associate in good faith.  Despite the danger, no blame.",
    line2:"Six in the third place means:  One sees the wagon dragged back,  The oxen halted,  A person's hair and nose cut off.  Not a good beginning, but a good end.",
    line1:"Nine in the second place means:  One meets one's lord in a narrow street.  No blame.",
    line0:"Nine at the beginning means:  Remorse disappears.  If you lose your horse, do not run after it;  It will come back of its own accord.  When you see evil people,  Guard yourself against mistakes."
  },
  hex39:{
    hexCode:"&#19942;",
    hexName:"39. Chien / Obstruction",
    allLines:["yin","yin","yang","yin","yang","yin"],
	judgment:"Obstruction.  The southwest furthers.  The northeast does not further.  It furthers one to see the great one.  Perseverance brings good fortune.",
	image:"Water on the mountain:  The image of Obstruction.  Thus the superior one turns their attention inward  And molds their character.",
    line5:"Six at the top means:  Going leads to obstructions,  Coming leads to great good fortune.  It furthers one to see the great one.",
    line4:"Nine in the fifth place means:  In the midst of the greatest obstructions,  Friends come.",
    line3:"Six in the fourth place means:  Going leads to obstructions,  Coming leads to union.",
    line2:"Nine in the third place means:  Going leads to obstructions;  Hence one comes back.",
    line1:"Six in the second place means:  The king's servant is beset by obstruction upon obstruction.  But it is not the servant's own fault.",
    line0:"Six at the beginning means:  Going leads to obstructions,  Coming meets with praise."
  },
  hex40:{
    hexCode:"&#19943;",
    hexName:"40. Hsieh / Deliverance",
    allLines:["yin","yang","yin","yang","yin","yin"],
	judgment:"Deliverance.  The southwest furthers.  If there is no longer anything where one has to go,  Return brings good fortune.  If there is still something where one has to go,  Hastening brings good fortune.",
	image:"Thunder and rain set in:  The image of Deliverance.  Thus the superior one pardons mistakes  And forgives misdeeds.",
    line5:"Six at the top means:  The prince shoots at a hawk on a high wall.  He kills it.  Everything serves to further.",
    line4:"Six in the fifth place means:  If only the superior one can deliver oneself,  it brings good fortune.  Thus the superior one proves to inferior people that the superior one is in earnest.",
    line3:"Nine in the fourth place means:  Deliver yourself from your great toe.  Then the companion comes,  And one you can trust.",
    line2:"Six in the third place means:  If one carries a burden on their back  And nonetheless rides in a carriage,  THey thereby encourage robbers to draw near.  Perseverance leads to humiliation.",
    line1:"Nine in the second place means:  One kills three foxes in the field  And receives a yellow arrow.  Perseverance brings good fortune.",
    line0:"Six at the beginning means:  Without blame."
  },
  hex41:{
    hexCode:"&#19944;",
    hexName:"41. Sun / Decrease",
    allLines:["yang","yang","yin","yin","yin","yang"],
	judgment:"Decrease combined with sincerity  Brings about supreme good fortune  Without blame.  One may be persevering in this.  It furthers one to undertake something.  How is this to be carried out?  One may use two small bowls for the sacrifice.",
	image:"At the foot of the mountain, the lake:  The image of Decrease.  Thus the superior one controls their anger  And restrains their instincts.",
    line5:"Nine at the top means:  If one is increased without depriving others,  There is no blame.  Perseverance brings good fortune.  It furthers one to undertake something.  One obtains servants  But no longer has a separate home.",
    line4:"Six in the fifth place means:  Someone does indeed increase them.  Ten pairs of tortoises cannot oppose it.  Supreme good fortune.",
    line3:"Six in the fourth place means:  If a man decreases his faults,  It makes the other hasten to come and rejoice.  No blame.",
    line2:"Six in the third place means:  When three people journey together,  Their number decreases by one,  When one man journeys alone,  He finds a companion.",
    line1:"Nine in the second place means:  Perseverance furthers.  To undertake something brings misfortune.  Without decreasing oneself,  One is able to bring increase to others.",
    line0:"Nine at the beginning means:  Going quickly when one's tasks are finished  Is without blame.  But one must reflect on how much one may decrease others."
  },
  hex42:{
    hexCode:"&#19945;",
    hexName:"42. I / Increase",
    allLines:["yang","yin","yin","yin","yang","yang"],
	judgment:"Increase.  It furthers one  To undertake something.  It furthers one to cross the great water.",
	image:"Wind and thunder:  the image of Increase.  Thus the superior one:  If one sees good, one imitates it;  If one has faults, one removes them.",
    line5:"Nine at the top means:  One brings increase to no one.  Indeed, someone even strikes one.  One does not keep their constantly steady.  Misfortune.",
    line4:"Nine in the fifth place means:  If in truth you have a kind heart, ask not.  Supreme good fortune.  Truly, kindness will be recognized as your virtue.",
    line3:"Six in the fourth place means:  If you walk in the middle  And report to the prince,  He will follow.  It furthers one to be used  In the removal of the capital.",
    line2:"Six in the third place means:  One is enriched through unfortunate events.  No blame, if you are sincere  And walk in the middle,  And report with a seal to the prince.",
    line1:"Six in the second place means:  Someone does indeed increase one;  Ten pairs of tortoises cannot oppose it.  Constant perseverance brings good fortune.  The king presents one before God.  Good fortune.",
    line0:"Nine at the beginning means:  It furthers one to accomplish great deeds.  Supreme good fortune.  No blame."
  },
  hex43:{
    hexCode:"&#19946;",
    hexName:"43. Kuai / Break-through (Resoluteness)",
    allLines:["yang","yang","yang","yang","yang","yin"],
	judgment:"Break-through.  One must resolutely make the matter known  At the court of the king.  It must be announced truthfully.  Danger.  It is necessary to notify one's own city.  It does not further to resort to arms.  It furthers to undertake something.",
	image:"The lake has risen up to heaven:  The image of Break-through.  Thus the superior one  Dispenses riches downward  And refrains from resting on their virtue.",
    line5:"Six at the top means:  No cry.  In the end misfortune comes.",
    line4:"Nine in the fifth place means:  In dealing with weeds,  Firm resolution is necessary.  Walking in the middle  Remains free of blame.",
    line3:"Nine in the fourth place means:  There is no skin on one's thighs,  And walking comes hard.  If a person were to allow oneself be led like a sheep,  Remorse would disappear.  But if these words are heard  They will not be believed.",
    line2:"Nine in the third place means:  To be powerful in the cheekbones  Brings misfortune.  The superior one is firmly resolved.  The superior one walks alone and is caught in the rain  Is bespattered,  And people murmur against them.  No blame.",
    line1:"Nine in the second place means:  A cry of alarm.  Arms at evening and at night.  Fear nothing.",
    line0:"Nine at the beginning means:  Mighty in the forward-striding toes.  When one goes and is not equal to the task,  One makes a mistake.  "
  },
  hex44:{
    hexCode:"&#19947;",
    hexName:"44. Kou / Coming to Meet",
    allLines:["yin","yang","yang","yang","yang","yang"],
	judgment:"Coming to Meet.  The maiden is powerful.  One should not marry such a maiden.",
	image:"Under heaven, wind:  The image of Coming to Meet.  Thus does the prince act when disseminating his commands.  And proclaiming them to the four quarters of heaven.",
    line5:"Nine at the top means:  He comes to meet with his horns.  Humiliation.  No blame.",
    line4:"NIne in the fifth place means:  A melon covered with willow leaves.  Hidden lines.  Then it drops down to one from heaven.",
    line3:"Nine in the fourth place means:  No fish in the tank.  This leads to misfortune.",
    line2:"Nine in the third place means:  There is no skin on one's thighs,  And walking comes hard.  If one is mindful of the danger,  No great mistake is made.",
    line1:"Nine in the second place means:  There is a fish in the tank.  No blame.  Does not further guests.",
    line0:"Six at the beginning means:  It must be checked with a break of bronze.  Perseverance brings good fortune.  If one lets it take its course, one experiences misfortune.  Even a lean pig has it in him to rage around."
  },
  hex45:{
    hexCode:"&#19948;",
    hexName:"45. Ts'ui / Gathering Together [Massing]",
    allLines:["yin","yin","yin","yang","yang","yin"],
	judgment:"Gathering Together. Success.  The king approaches his temple.  It furthers one to see the great one.  This brings success.  Perseverance furthers.  To bring great offerings creates good fortune.  It furthers one to undertake something.",
	image:"Over the earth, the lake:  The image of Gathering Together.  Thus the superior one renews one's weapons  In order to meet the unforeseen.",
    line5:"Six at the top means:  Lamenting and sighing, floods of tears.  No blame.",
    line4:"Nine in the fifth place means:  If in gathering together one has position,  This brings no blame.  If there are some who are not yet sincerely in the work,  Sublime and enduring perseverance is needed.  Then remorse disappears.",
    line3:"Nine in the fourth place means:  Great good fortune.  No blame.",
    line2:"Six in the third place means:  Gathering together amid sighs.  Nothing that would further.  Going is without blame.  Slight humiliation.",
    line1:"Six in the second place means:  Letting oneself be drawn  Brings good fortune and remains blameless.  If one is sincere,  It furthers one to bring even a small offering.",
    line0:"Six at the beginning means:  If you are sincere, but not to the end,  There will sometimes be confusions, sometimes gathering together.  If you call out,  Then after one grasp of the hand you can laugh again.  Regret not.  Going is without blame."
  },
  hex46:{
    hexCode:"&#19949;",
    hexName:"46. Shêng / Pushing Upward",
    allLines:["yin","yang","yang","yin","yin","yin"],
	judgment:"Pushing Upward has supreme success.  One must see the great one.  Fear not.  Departure toward the south  Brings good fortune.",
	image:"Within the earth, wood grows:  The image of Pushing Upward.  Thus the superior one of devoted character  Heaps up small things  In order to achieve something high and great.",
    line5:"Six at the top means:  Pushing upward in darkness.  It furthers one  To be unremittingly persevering.",
    line4:"Six in the fifth place means:  Perseverance brings good fortune.  One pushes upward by steps.",
    line3:"Six in the fourth place means:  The king offers one Mount Ch'i.  Good fortune.  No blame.",
    line2:"Nine in the third place means:  One pushes upward into an empty city.",
    line1:"Nine in the second place means:  If one is sincere,  It furthers one to bring even a small offering.  No blame.",
    line0:"Six at the beginning means:  Pushing upward that meets with confidence  Brings great good fortune."
  },
  hex47:{
    hexCode:"&#19950;",
    hexName:"47. K'un / Oppression (Exhaustion)",
    allLines:["yin","yang","yin","yang","yang","yin"],
	judgment:"Oppression.  Success.  Perseverance.  The great one brings about good fortune.  No blame.  When one has something to say,  It is not believed.",
	image:"There is no water in the lake:  The image of Exhaustion.  Thus the superior one stakes one's life  On following one's will.",
    line5:"Six at the top means:  One is oppressed by creeping vines.  One moves uncertainly and says, 'Movement brings remorse.'  If one feels remorse over this and makes a start,  Good fortune comes.",
    line4:"Nine in the fifth place means:  One's nose and feet are cut off.  Oppression at the hands of the one with the purple knee bands.  Joy comes softly.  It furthers one to make offering and libations.",
    line3:"Nine in the fourth place means:  One comes very quietly, oppressed in a golden carriage.  Humiliation, but the end is reached.",
    line2:"Six in the third place means:  One permits oneself to be oppressed by stone,  And leans on thorns and thistles.  One enters their house and does not see their spouse.  Misfortune.",
    line1:"Nine in the second place means:  One is oppressed while at meat and drink.  The one with the scarlet knee bands is just coming.  It furthers one to offer sacrifice.  To set forth brings misfortune.  No blame.",
    line0:"Six at the beginning means:  One sits oppressed under a bare tree  And strays into a gloomy valley.  For three years one sees nothing."
  },
  hex48:{
    hexCode:"&#19951;",
    hexName:"48. Ching / The Well",
    allLines:["yin","yang","yang","yin","yang","yin"],
	judgment:"The Well.  The town may be changed,  But the well cannot be changed.  It neither decreases nor increases.  They come and go and draw from the well.  If one gets down almost to the water  And the rope does not go all the way,  Or the jug breaks, it brings misfortune.",
	image:"Water over wood:  the image of The Well.  Thus the superior one encourages the people at their work,  And exhorts them to help one another.",
    line5:"Six at the top means:  One draws from the well  Without hindrance.  It is dependable.  Supreme good fortune.",
    line4:"Nine in the fifth place means:  In the well there is a clear, cold spring  From which one can drink.",
    line3:"Six in the fourth place means:  The well is being lined.  No blame.",
    line2:"Nine in the third place means:  The well is cleaned, but no one drinks from it.  This is my heart's sorrow,  For one might draw from it.  If the king were clear-minded,  Good fortune might be enjoyed in common.",
    line1:"Nine in the second place means:  At the wellhole one shoots fishes.  The jug is broken and leaks.",
    line0:"Six at the beginning means:  One does not drink the mud of the well.  No animals come to an old well."
  },
  hex49:{
    hexCode:"&#19952;",
    hexName:"49. Ko / Revolution (Molting)",
    allLines:["yang","yin","yang","yang","yang","yin"],
	judgment:"Revolution.  On your own day  You are believed.  Supreme success,  Furthering through perseverance.  Remorse disappears.",
	image:"Fire in the lake:  the image of Revolution.  Thus the superior one  Sets the calendar in order  And makes the seasons clear.",
    line5:"Six at the top means:  The superior one changes like a panther.  The inferior one molts in the face.  Starting brings misfortune.  To remain persevering brings good fortune.",
    line4:"Nine in the fifth place means:  The great one changes like a tiger.  Even before one questions the oracle  One is believed.",
    line3:"Nine in the fourth place means:  Remorse disappears.  Others believe one.  Changing the form of government brings good fortune.",
    line2:"Nine in the third place means:  Starting brings misfortune.  Perseverance brings danger.  When talk of revolution has gone the rounds three times,  One may commit oneself,  And others will believe.",
    line1:"Six in the second place means:  When one's own day comes, one may create revolution.  Starting brings good fortune.  No blame.",
    line0:"Nine at the beginning means:  Wrapped in the hide of a yellow cow."
  },
  hex50:{
    hexCode:"&#19953;",
    hexName:"50. Ting / The Cauldron",
    allLines:["yin","yang","yang","yang","yin","yang"],
	judgment:"The Cauldron.  Supreme good fortune.  Success.",
	image:"Fire over wood:  The image of The Cauldron.  Thus the superior one consolidates one's fate  By making one's position correct.",
    line5:"Nine at the top means:  The ting has rings of jade.  Great good fortune.  Nothing that would not act to further.",
    line4:"Six in the fifth place means:  The ting has yellow handles, golden carrying rings.  Perseverance furthers.",
    line3:"Nine in the fourth place means:  The legs of the ting are broken.  The prince's meal is spilled  And his person is soiled.  Misfortune.",
    line2:"Nine in the third place means:  The handle of the ting is altered.  One is impeded in one's way of life.  The fat of the pheasant is not eaten.  Once rain falls, remorse is spent.  Good fortune comes in the end.",
    line1:"Nine in the second place means:  There is food in the ting.  My comrades are envious,  But they cannot harm me.  Good fortune.",
    line0:"Six at the beginning means:  A tin with legs upturned.  Furthers removal of stagnating stuff.  One takes a concubine for the sake of her son.  No blame."
  },
  hex51:{
    hexCode:"&#19954;",
    hexName:"51. Chên / The Arousing (Shock, Thunder)",
    allLines:["yang","yin","yin","yang","yin","yin"],
	judgment:"Shock brings success.  Shock comes -- oh, oh!  Laughing words -- ha, ha!  The shock terrifies for a hundred miles,  And one does not let fall the sacrificial spoon and chalice.",
	image:"Thunder repeated:  the image of Shock.  Thus in fear and trembling  The superior one sets one's life in order  And examines oneself.",
    line5:"Six at the top means:  Shock brings ruin and terrified gazing around.  Going ahead brings misfortune.  If it has not yet touched one's own body  But has reached one's neighbor first,  There is no blame.  One's comrades have something to talk about.",
    line4:"Six in the fifth place means:  Shock goes hither and thither.  Danger.  However, nothing at all is lost.  Yet there are things to be done.",
    line3:"Nine in the fourth place means:  Shock is mired.",
    line2:"Six in the third place means:  Shock comes and makes one distraught.  If shock spurs to action  One remains free of misfortune.",
    line1:"Six in the second place means:  Shock comes bringing danger.  A hundred thousand times  You lose your treasures  And must climb the nine hills.",
    line0:"Nine at the beginning means:  Shock comes -- oh, oh!  Then follow laughing words -- ha, ha!  Good fortune."
  },
  hex52:{
    hexCode:"&#19955;",
    hexName:"52. Kên / Keeping Still, Mountain",
    allLines:["yin","yin","yang","yin","yin","yang"],
	judgment:"Keeping Still.  Keeping one's back still  So that one no longer feels one's body.  One goes into one's courtyard  And does not see one's people.  No blame.",
	image:"Mountains standing close together:  The image of Keeping Still.  Thus the superior one  Does not permit one's thoughts  To go beyond one's situation.",
    line5:"Nine at the top means:  Noblehearted keeping still.  Good fortune.",
    line4:"Six in the fifth place means:  Keeping one's jaws still.  The words have order.  Remorse disappears.",
    line3:"Six in the fourth place means:  Keeping one's trunk still.  No blame.",
    line2:"Nine in the third place means:  Keeping one's hips still.  Making one's sacrum stiff.  Dangerous.  The heart suffocates.",
    line1:"Six in the second place means:  Keeping one's calves still.  One cannot rescue they whom one follows.  One's heart is not glad.",
    line0:"Six at the beginning means:  Keeping one's toes still.  No blame.  Continued perseverance furthers."
  },
  hex53:{
    hexCode:"&#19956;",
    hexName:"53. Chien / Development (Gradual Progress)",
    allLines:["yin","yin","yang","yin","yang","yang"],
	judgment:"Development.  The maiden  Is given in marriage.  Good fortune.  Perseverance furthers.",
	image:"On the mountain, a tree:  The image of Development.  Thus the superior one abides in dignity and virtue,  In order to improve the mores.",
    line5:"Nine at the top means:  The wild goose gradually draws near the cloud heights.  Its feathers can be used for the sacred dance.  Good fortune.",
    line4:"Nine in the fifth place means:  The wild goose gradually draws near the summit.  For three years the woman has no child.  In the end nothing can hinder her.  Good fortune.",
    line3:"Six in the fourth place means:  The wild goose gradually draws near the tree.  Perhaps it will find a flat branch.  No blame.",
    line2:"Nine in the third place means:  The wild goose gradually draws near the plateau.  The man goes forth and does not return.  The woman carries a child but does not bring it forth.  Misfortune.  It furthers one to fight off robbers.",
    line1:"Six in the second place means:  The wild goose gradually draws near the cliff.  Eating and drinking in peace and concord.  Good fortune.",
    line0:"Six at the beginning means:  The wild goose gradually draws near the shore.  The young son is in danger.  There is talk.  No blame."
  },
  hex54:{
    hexCode:"&#19957;",
    hexName:"54. Kuei Mei / The Marrying Maiden",
    allLines:["yang","yang","yin","yang","yin","yin"],
	judgment:"The Marrying Maiden.  Undertakings bring misfortune.  Nothing that would further.",
	image:"Thunder over the lake:  The image of The Marrying Maiden.  Thus the superior one  Understands the transitory  In the light of the eternity of the end.",
    line5:"Six at the top means:  The woman holds the basket, but there are no fruits in it.  The man stabs the sheep, but no blood flows.  Nothing that acts to further.",
    line4:"Six in the fifth place means:  The sovereign I gave his daughter in marriage.  The embroidered garments of the princess  Were not as gorgeous  As those of the servingmaid.  The moon that is nearly full  Brings good fortune.",
    line3:"Nine in the fourth place means:  The marrying maiden draws out the allotted time.  A late marriage comes in due course.",
    line2:"Six in the third place means:  The marrying maiden as a slave.  She marries as a concubine.",
    line1:"Nine in the second place means:  A one-eyed person who is able to see.  The perseverance of a solitary individual furthers.",
    line0:"Nine at the beginning means:  The marrying maiden as a concubine.  A lame person who is able to tread.  Undertakings bring good fortune."
  },
  hex55:{
    hexCode:"&#19958;",
    hexName:"55. Fêng / Abundance [Fullness]",
    allLines:["yang","yin","yang","yang","yin","yin"],
	judgment:"Abundance has success.  The king attains abundance.  Be not sad.  Be like the sun at midday.",
	image:"Both thunder and lightning come:  The image of Abundance.  Thus the superior one decides lawsuits  And carries out punishments.",
    line5:"Six at the top means:  One's house is in a state of abundance.  One screens off one's family.  One peers through the gate  And no longer perceives anyone.  For three years one sees nothing.  Misfortune.",
    line4:"Six in the fifth place means:  Lines are coming,  Blessing and fame draw near.  Good fortune.",
    line3:"Nine in the fourth place means:  The curtain is of such fullness  That the polestars can be seen at noon.  One meets one's ruler, who is of like kind.  Good fortune.",
    line2:"Nine in the third place means:  The underbrush is of such abundance  That the small stars can be seen at noon.  One breaks one's right arm.  No blame.",
    line1:"Six in the second place means:  The curtain is of such fullness  That the polestars can be seen at noon.  Through going one meets with mistrust and hate,  If one rouses another through truth,  Good fortune comes.",
    line0:"Nine at the beginning means:  When one meets one's destined ruler,  They can be together ten days,  And it is not a mistake.  Going meets with recognition."
  },
  hex56:{
    hexCode:"&#19959;",
    hexName:"56. Lü / The Wanderer",
    allLines:["yin","yin","yang","yang","yin","yang"],
	judgment:"The Wanderer.  Success through smallness.  Perseverance brings good fortune  To the wanderer.",
	image:"Fire on the mountain:  The image of The Wanderer.  Thus the superior one  Is clear-minded and cautious  In imposing penalties,  And protracts no lawsuits.",
    line5:"Nine at the top means:  The bird's nest burns up.  The wanderer laughs at first,  Then must needs lament and weep.  Through carelessness one loses their cow.  Misfortune.",
    line4:"Six in the fifth place means:  One shoots a pheasant.  It drops with the first arrow.  In the end this brings both praise and office.",
    line3:"Nine in the fourth place means:  The wanderer rests in a shelter.  One obtains one's property and an ax.  My heart is not glad.",
    line2:"Nine in the third place means:  The wanderer's inn burns down.  One loses the steadfastness of one's young servant.  Danger.",
    line1:"Six in the second place means:  The wanderer comes to an inn  bring one's property.  One wins the steadfastness of a young servant.",
    line0:"Six at the beginning means:  If the wanderer busies oneself with trivial things,  One draws down misfortune upon oneself."
  },
  hex57:{
    hexCode:"&#19960;",
    hexName:"57. Sun / The Gentle (The Penetrating, Wind)",
    allLines:["yin","yang","yang","yin","yang","yang"],
	judgment:"The Gentle.  Success through what is small.  It furthers one to have somewhere to go.  It furthers one to see the great one.",
	image:"Winds following one upon the other:  The image of The Gently Penetrating.  Thus the superior one  Spreads one's commands abroad  And carries out one's undertakings.",
    line5:"Nine at the top means:  Penetration under the bed.  One loses one's property and one's ax.  Perseverance brings misfortune.",
    line4:"Nine in the fifth place means:  Perseverance brings good fortune.  Remorse vanishes.  Nothing that does not further.  No beginning, but an end.  Before the change, three days.  After the change, three days.  Good fortune.",
    line3:"Six in the fourth place means:  Remorse vanishes.  During the hunt  Three kinds of game are caught.",
    line2:"Nine in the third place means:  Repeated penetration.  Humiliation.",
    line1:"Nine in the second place means:  Penetration under the bed.  Priests and magicians are used in great number.  Good fortune.  No blame.",
    line0:"Six at the beginning means:  In advancing and in retreating,  The perseverance of a warrior furthers."
  },
  hex58:{
    hexCode:"&#19961;",
    hexName:"58. Tui / The Joyous, Lake",
    allLines:["yang","yang","yin","yang","yang","yin"],
	judgment:"The Joyous.  Success.  Perseverance is favorable.",
	image:"Lakes resting one on the other:  The image of The Joyous.  Thus the superior one joins with one's friends  For discussion and practice.",
    line5:"Six at the top means:  Seductive joyousness.",
    line4:"Nine in the fifth place means:  Sincerity toward disintegrating influences is dangerous.",
    line3:"Nine in the fourth place means:  Joyousness that is weighed is not at peace.  After ridding oneself of mistakes one has joy.",
    line2:"Six in the third place means:  Coming joyousness.  Misfortune.",
    line1:"Nine in the second place means:  Sincere joyousness.  Good fortune.  Remorse disappears.",
    line0:"Nine at the beginning means:  Contented joyousness.  Good fortune."
  },
  hex59:{
    hexCode:"&#19962;",
    hexName:"59. Huan / Dispersion [Dissolution]",
    allLines:["yin","yang","yin","yin","yang","yang"],
	judgment:"Dispersion.  Success.  The king approaches his temple.  It furthers one to cross the great water.  Perseverance furthers.",
	image:"The wind drives over the water:  The image of Dispersion.  Thus the kings of old sacrificed to the Lord  And built temples.",
    line5:"Nine at the top means:  One dissolves one's blood.  Departing, keeping at a distance, going out,  Is without blame.",
    line4:"Nine in the fifth place means:  One's loud cries are as dissolving as sweat.  Dissolution!  A king abides without blame.",
    line3:"Six in the fourth place means:  One dissolves one's bond with one's group.  Supreme good fortune.  Dispersion leads in turn to accumulation.  This is something that ordinary people do not think of.",
    line2:"Six in the third place means:  One dissolves oneself.  No remorse.",
    line1:"Nine in the second place means:  At the dissolution  One hurries to that which supports one.  Remorse disappears.",
    line0:"Six at the beginning means:  One brings help with the strength of a horse.  Good fortune."
  },
  hex60:{
    hexCode:"&#19963;",
    hexName:"60. Chieh / Limitation",
    allLines:["yang","yang","yin","yin","yang","yin"],
	judgment:"Limitation.  Success.  Galling limitation must not be persevered in.",
	image:"Water over the lake:  the image of Limitation.  Thus the superior one  Creates number and measure,  And examines the nature of virtue and correct conduct.",
    line5:"Six at the top means:  Galling limitation.  Perseverance brings misfortune.  Remorse disappears.",
    line4:"Nine in the fifth place means:  Sweet limitation brings good fortune.  Going brings esteem.",
    line3:"Six in the fourth place means:  Contented limitation.  Success.",
    line2:"Six in the third place means:  One who knows no limitation  Will have cause to lament.  No blame.",
    line1:"Nine in the second place means:  Not going out of the gate and the courtyard  Brings misfortune.",
    line0:"Nine at the beginning means:  Not going out of the door and the courtyard  Is without blame."
  },
  hex61:{
    hexCode:"&#19964;",
    hexName:"61. Chung Fu / Inner Truth",
    allLines:["yang","yang","yin","yin","yang","yang"],
	judgment:"Inner Truth.  Pigs and fishes.  Good fortune.  It furthers one to cross the great water.  Perseverance furthers.",
	image:"Wind over the lake:  the image of Inner Truth.  Thus the superior one discusses criminal cases  In order to delay executions.",
    line5:"Nine at the top means:  Cockcrow penetrating to heaven.  Perseverance brings misfortune.",
    line4:"Nine in the fifth place means:  One possesses truth, which links together.  No blame.",
    line3:"Six in the fourth place means:  The moon nearly at the full.  The team horse goes astray.  No blame.",
    line2:"Six in the third place means:  One finds a comrade.  Now one beats the drum, now one stops.  Now one sobs, now one sings.",
    line1:"Nine in the second place means:  A crane calling in the shade.  Its young answers it.  I have a good goblet.  I will share it with you.",
    line0:"Nine at the beginning means:  Being prepared brings good fortune.  If there are secret designs, it is disquieting."
  },
  hex62:{
    hexCode:"&#19965;",
    hexName:"62. Hsiao Ku / Preponderance of the Small",
    allLines:["yin","yin","yang","yang","yin","yin"],
	judgment:"Preponderance of the Small.  Success.  Perseverance furthers.  Small things may be done; great things should not be done.  The flying bird brings the message:  It is not well to strive upward,  It is well to remain below.  Great good fortune.",
	image:"Thunder on the mountain:  The image of Preponderance of the Small.  Thus in one's conduct the superior one gives preponderance to reverence.  In bereavement, one gives preponderance to grief.  In one's expenditures, one gives preponderance to thrift.",
    line5:"Six at the top means:  One passes another by, not meeting that person.  The flying bird leaves one.  Misfortune.  This means bad luck and injury.",
    line4:"Six in the fifth place means:  Dense clouds,  No rain from our western territory.  The prince shoots and hits someone who is in the cave.",
    line3:"Nine in the fourth place means:  No blame.  One meets another without passing by.  Going brings danger.  One must be on guard.  Do not act.  Be constantly persevering.",
    line2:"Nine in the third place means:  If one is not extremely careful,  Somebody may come up from behind and strike one.  Misfortune.",
    line1:"Six in the second place means:  She passes by her ancestor  And meets her ancestress.  He does not reach his prince  And meets the official.  No blame.",
    line0:"Six at the beginning means:  The bird meets with misfortune through flying."
  },
  hex63:{
    hexCode:"&#19966;",
    hexName:"63. Chi Chi / After Completion",
    allLines:["yang","yin","yang","yin","yang","yin"],
	judgment:"After Completion.  Success in small matters.  Perseverance furthers.  At the beginning good fortune,  At the end disorder.",
	image:"Water over fire:  the image of the condition  In After Completion.  Thus the superior one  Takes thought of misfortune  And arms oneself against it in advance.",
    line5:"Six at the top means:  One gets one's head in the water.  Danger.",
    line4:"Nine in the fifth place means:  The neighbor in the east who slaughters an ox  Does not attain as much real happiness  As the neighbor in the west  With their small offering.",
    line3:"Six in the fourth place means:  The finest clothes turn to rags.  Be careful all day long.",
    line2:"Nine in the third place means:  The Illustrious Ancestor  Disciplines the Devil's Country.  After three years it is conquered.  Inferior people must not be employed.",
    line1:"Six in the second place means:  The woman loses the curtain of her carriage.  Do not run after it;  On the seventh day you will get it.",
    line0:"Nine at the beginning means:  One brakes one's wheels.  One gets one's tail in the water.  No blame."
  },
  hex64:{
    hexCode:"&#19967;",
    hexName:"64. Wei Chi / Before Completion",
    allLines:["yin","yang","yin","yang","yin","yang"],
	judgment:"Before Completion.  Success.  But if the little fox, after nearly completing the crossing,  Gets its tail in the water,  There is nothing that would further.",
	image:"Fire over water:  The image of the condition before transition.  Thus the superior one is careful  In the differentiation of things,  So that each finds its place.",
    line5:"Nine at the top means:  There is drinking of wine.  In genuine confidence.  No blame.  But if one wets one's head,  One loses it, in truth.",
    line4:"Six in the fifth place means:  Perseverance brings good fortune.  No remorse.  The light of the superior one is true.  Good fortune.",
    line3:"Nine in the fourth place means:  Perseverance brings good fortune.  Remorse disappears.  Shock, thus to discipline the Devil's Country.  For three years, great realms are awarded.",
    line2:"Six in the third place means:  Before completion, attack brings misfortune.  It furthers one to cross the great water.",
    line1:"Nine in the second place means:  One brakes one's wheels.  Perseverance brings good fortune.",
    line0:"Six at the beginning means:  One gets one's tail in the water.  Humiliating."
  }
} // hexagrams
